package constants

const (
	LOG_EVENT_PASSWORD_CHANGED         = "PASSWORD CHANGED"
	LOG_EVENT_PASSWORD_RESET_INITIATED = "PASSWORD RESET INITIATED"
	LOG_EVENT_PASSWORD_RESET           = "PASSWORD RESET"

	LOG_EVENT_ACCOUNT_CREATED      = "ACCOUNT CREATED"
	LOG_EVENT_ACCOUNT_ID_CHANGED   = "ACCOUNT ID CHANGED"
	LOG_EVENT_ACCOUNT_DELETED      = "ACCOUNT DELETED"
	LOG_EVENT_ACCOUNT_ROLE_ADDED   = "ACCOUNT ROLE ADDED"
	LOG_EVENT_ACCOUNT_ROLE_REMOVED = "ACCOUNT ROLE REMOVED"
	LOG_EVENT_PROFILE_SAVED        = "PROFILE SAVED"
	LOG_EVENT_PROFILE_REMOVED      = "PROFILE REMOVED"

	// Auth related:
	LOG_EVENT_LOGIN_SUCCESS                    = "LOGIN SUCCESS"
	LOG_EVENT_CONTACT_VERIFIED                 = "CONTACT VERIFIED"
	LOG_EVENT_TOKEN_REFRESH_SUCCESS            = "TOKEN REFRESH SUCCESS"
	LOG_EVENT_AUTH_WRONG_ACCOUNT_ID            = "AUTH WRONG ACCOUNT ID"
	LOG_EVENT_AUTH_WRONG_PASSWORD              = "AUTH WRONG PASSWORD"
	LOG_EVENT_LOGIN_ATTEMPT_ON_BLOCKED_ACCOUNT = "LOGIN ATTEMPT ON BLOCKED ACCOUNT"
	LOG_EVENT_AUTH_WRONG_VERIFICATION_CODE     = "AUTH WRONG VERIFICATION CODE"

	// Study event:
	LOG_EVENT_STUDY_CREATION     = "STUDY CREATION"
	LOG_EVENT_GET_STUDY          = "GET STUDY"
	LOG_EVENT_STUDY_UPDATE       = "STUDY UPDATE"
	LOG_EVENT_STUDY_DELETION     = "STUDY DELETED"
	LOG_EVENT_STUDY_MEMBER       = "STUDY MEMBER"
	LOG_EVENT_SAVE_SURVEY        = "SAVE SURVEY"
	LOG_EVENT_REMOVE_SURVEY      = "REMOVE SURVEY"
	LOG_EVENT_DOWNLOAD_RESPONSES = "DOWNLOAD RESPONSES"
	LOG_EVENT_GET_SURVEY_DEF     = "GET SURVEY DEFINITION"
	LOG_EVENT_WRONG_PROFILE_ID   = "WRONG PROFILE ID"

	// Messaging:
	LOG_EVENT_GET_EMAIL_TEMPLATES   = "GET EMAIL TEMPLATES"
	LOG_EVENT_SAVE_EMAIL_TEMPLATE   = "SAVE EMAIL TEMPLATE"
	LOG_EVENT_REMOVE_EMAIL_TEMPLATE = "REMOVE EMAIL TEMPLATE"
	LOG_EVENT_SAVE_AUTO_MESSAGE     = "SAVE AUTO MESSAGE"
	LOG_EVENT_GET_AUTO_MESSAGES     = "GET AUTO MESSAGES"
	LOG_EVENT_REMOVE_AUTO_MESSAGE   = "REMOVE AUTO MESSAGE"
	LOG_EVENT_BULK_MESSAGE_SEND     = "BULK MESSAGE SEND"
)
