package constants

const (
	LOG_EVENT_PASSWORD_CHANGED         = "PASSWORD CHANGED"
	LOG_EVENT_PASSWORD_RESET_INITIATED = "PASSWORD RESET INITIATED"
	LOG_EVENT_PASSWORD_RESET           = "PASSWORD RESET"

	LOG_EVENT_ACCOUNT_CREATED      = "ACCOUNT CREATED"
	LOG_EVENT_ACCOUNT_ID_CHANGED   = "ACCOUNT ID CHANGED"
	LOG_EVENT_ACCOUNT_DELETED      = "ACCOUNT DELETED"
	LOG_EVENT_ACCOUNT_ROLE_ADDED   = "ACCOUNT ROLE ADDED"
	LOG_EVENT_ACCOUNT_ROLE_REMOVED = "ACCOUNT ROLE REMOVED"
	LOG_EVENT_PROFILE_SAVED        = "PROFILE SAVED"
	LOG_EVENT_PROFILE_REMOVED      = "PROFILE REMOVED"

	// Auth related:
	LOG_EVENT_LOGIN_SUCCESS                    = "LOGIN SUCCESS"
	LOG_EVENT_CONTACT_VERIFIED                 = "CONTACT VERIFIED"
	LOG_EVENT_TOKEN_REFRESH_SUCCESS            = "TOKEN REFRESH SUCCESS"
	LOG_EVENT_AUTH_WRONG_ACCOUNT_ID            = "AUTH WRONG ACCOUNT ID"
	LOG_EVENT_AUTH_WRONG_PASSWORD              = "AUTH WRONG PASSWORD"
	LOG_EVENT_LOGIN_ATTEMPT_ON_BLOCKED_ACCOUNT = "LOGIN ATTEMPT ON BLOCKED ACCOUNT"
	LOG_EVENT_AUTH_WRONG_VERIFICATION_CODE     = "AUTH WRONG VERIFICATION CODE"

	// Study event:
	LOG_EVENT_STUDY_CREATION     = "STUDY CREATION"
	LOG_EVENT_STUDY_UPDATE       = "STUDY UPDATE"
	LOG_EVENT_SAVE_SURVEY        = "SAVE SURVEY"
	LOG_EVENT_REMOVE_SURVEY      = "REMOVE SURVEY"
	LOG_EVENT_DOWNLOAD_RESPONSES = "DOWNLOAD RESPONSES"
)
